// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Channel struct {
	ID        uuid.UUID
	Name      string
	BaseUrl   string
	ApiKey    string
	KeyPrefix string
	Protocols []string
	Currency  string
	Note      string
	Disabled  bool
	LastTest  []byte
	CreatedAt time.Time
}

type ChannelModel struct {
	ID               uuid.UUID
	ChannelID        uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

type Role struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
	CreatedAt   time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	CreatedAt    time.Time
	RoleID       uuid.UUID
}
