// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
select count(*) from users where role_id = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one
insert into channels (name, base_url, api_key, key_prefix, protocols, currency, note)
values ($1, $2, $3, $4, $5, $6, $7)
returning id
`

type CreateChannelParams struct {
	Name      string
	BaseUrl   string
	ApiKey    string
	KeyPrefix string
	Protocols []string
	Currency  string
	Note      string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.KeyPrefix,
		arg.Protocols,
		arg.Currency,
		arg.Note,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createChannelModel = `-- name: CreateChannelModel :one
insert into channel_models (channel_id, name, input_price, output_price, cached_input_price)
values ($1, $2, $3, $4, $5)
returning id, name, input_price, output_price, cached_input_price, created_at
`

type CreateChannelModelParams struct {
	ChannelID        uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
}

type CreateChannelModelRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) CreateChannelModel(ctx context.Context, arg CreateChannelModelParams) (CreateChannelModelRow, error) {
	row := q.db.QueryRow(ctx, createChannelModel,
		arg.ChannelID,
		arg.Name,
		arg.InputPrice,
		arg.OutputPrice,
		arg.CachedInputPrice,
	)
	var i CreateChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
insert into roles (name, permissions)
values ($1, $2)
returning id, name, built_in, permissions
`

type CreateRoleParams struct {
	Name        string
	Permissions []byte
}

type CreateRoleRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Permissions)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
insert into users (username, password_hash, role_id)
values ($1, $2, $3)
returning id
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	RoleID       uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.RoleID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
delete from channels where id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelModel = `-- name: DeleteChannelModel :execrows
delete from channel_models where id = $1 and channel_id = $2
`

type DeleteChannelModelParams struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
}

func (q *Queries) DeleteChannelModel(ctx context.Context, arg DeleteChannelModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelModel, arg.ID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
delete from sessions where expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
delete from sessions where user_id = $1 and token_hash <> $2
`

type DeleteOtherUserSessionsParams struct {
	UserID    uuid.UUID
	TokenHash []byte
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.TokenHash)
	return err
}

const deleteRole = `-- name: DeleteRole :execrows
delete from roles where id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
delete from sessions where user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getChannel = `-- name: GetChannel :one
select c.id, c.name, c.base_url, c.key_prefix, c.protocols, c.currency, c.note,
       c.disabled, c.last_test, c.created_at,
       (select count(*) from channel_models m where m.channel_id = c.id) as model_count
from channels c
where c.id = $1
`

type GetChannelRow struct {
	ID         uuid.UUID
	Name       string
	BaseUrl    string
	KeyPrefix  string
	Protocols  []string
	Currency   string
	Note       string
	Disabled   bool
	LastTest   []byte
	CreatedAt  time.Time
	ModelCount int64
}

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.KeyPrefix,
		&i.Protocols,
		&i.Currency,
		&i.Note,
		&i.Disabled,
		&i.LastTest,
		&i.CreatedAt,
		&i.ModelCount,
	)
	return i, err
}

const getChannelModel = `-- name: GetChannelModel :one
select id, name, input_price, output_price, cached_input_price, created_at
from channel_models
where id = $1 and channel_id = $2
`

type GetChannelModelParams struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
}

type GetChannelModelRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) GetChannelModel(ctx context.Context, arg GetChannelModelParams) (GetChannelModelRow, error) {
	row := q.db.QueryRow(ctx, getChannelModel, arg.ID, arg.ChannelID)
	var i GetChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelSecret = `-- name: GetChannelSecret :one
select id, base_url, api_key, protocols from channels where id = $1
`

type GetChannelSecretRow struct {
	ID        uuid.UUID
	BaseUrl   string
	ApiKey    string
	Protocols []string
}

// 连通测试专用：整个代码库唯一读取 api_key 明文的查询，结果绝不进任何响应体
func (q *Queries) GetChannelSecret(ctx context.Context, id uuid.UUID) (GetChannelSecretRow, error) {
	row := q.db.QueryRow(ctx, getChannelSecret, id)
	var i GetChannelSecretRow
	err := row.Scan(
		&i.ID,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Protocols,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
select id, name, built_in, permissions from roles where id = $1
`

type GetRoleRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (GetRoleRow, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i GetRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
select id, name, built_in, permissions from roles where name = $1
`

type GetRoleByNameRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i GetRoleByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
select u.id, u.username, r.name as role_name, r.permissions
from sessions s
join users u on u.id = s.user_id
join roles r on r.id = u.role_id
where s.token_hash = $1 and s.expires_at > now()
`

type GetSessionUserRow struct {
	ID          uuid.UUID
	Username    string
	RoleName    string
	Permissions []byte
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RoleName,
		&i.Permissions,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select u.id, u.username, u.role_id, r.name as role_name, u.created_at
from users u
join roles r on r.id = u.role_id
where u.id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	Username  string
	RoleID    uuid.UUID
	RoleName  string
	CreatedAt time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RoleID,
		&i.RoleName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select u.id, u.username, u.password_hash
from users u
where u.username = $1
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
select password_hash from users where id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const listChannelModels = `-- name: ListChannelModels :many
select id, name, input_price, output_price, cached_input_price, created_at
from channel_models
where channel_id = $1
order by created_at
`

type ListChannelModelsRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) ListChannelModels(ctx context.Context, channelID uuid.UUID) ([]ListChannelModelsRow, error) {
	rows, err := q.db.Query(ctx, listChannelModels, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelModelsRow
	for rows.Next() {
		var i ListChannelModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InputPrice,
			&i.OutputPrice,
			&i.CachedInputPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
select c.id, c.name, c.base_url, c.key_prefix, c.protocols, c.currency, c.note,
       c.disabled, c.last_test, c.created_at,
       (select count(*) from channel_models m where m.channel_id = c.id) as model_count
from channels c
order by c.created_at
`

type ListChannelsRow struct {
	ID         uuid.UUID
	Name       string
	BaseUrl    string
	KeyPrefix  string
	Protocols  []string
	Currency   string
	Note       string
	Disabled   bool
	LastTest   []byte
	CreatedAt  time.Time
	ModelCount int64
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.KeyPrefix,
			&i.Protocols,
			&i.Currency,
			&i.Note,
			&i.Disabled,
			&i.LastTest,
			&i.CreatedAt,
			&i.ModelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
select id, name, built_in, permissions from roles order by created_at
`

type ListRolesRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BuiltIn,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select u.id, u.username, u.role_id, r.name as role_name, u.created_at
from users u
join roles r on r.id = u.role_id
order by u.created_at
`

type ListUsersRow struct {
	ID        uuid.UUID
	Username  string
	RoleID    uuid.UUID
	RoleName  string
	CreatedAt time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.RoleID,
			&i.RoleName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :execrows
update channels set
    name       = coalesce($1, name),
    base_url   = coalesce($2, base_url),
    api_key    = coalesce($3, api_key),
    key_prefix = coalesce($4, key_prefix),
    protocols  = coalesce($5, protocols),
    currency   = coalesce($6, currency),
    note       = coalesce($7, note),
    disabled   = coalesce($8, disabled)
where id = $9
`

type UpdateChannelParams struct {
	Name      *string
	BaseUrl   *string
	ApiKey    *string
	KeyPrefix *string
	Protocols []string
	Currency  *string
	Note      *string
	Disabled  *bool
	ID        uuid.UUID
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannel,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.KeyPrefix,
		arg.Protocols,
		arg.Currency,
		arg.Note,
		arg.Disabled,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelLastTest = `-- name: UpdateChannelLastTest :execrows
update channels set last_test = $2 where id = $1
`

type UpdateChannelLastTestParams struct {
	ID       uuid.UUID
	LastTest []byte
}

func (q *Queries) UpdateChannelLastTest(ctx context.Context, arg UpdateChannelLastTestParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelLastTest, arg.ID, arg.LastTest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelModel = `-- name: UpdateChannelModel :one
update channel_models
set name = $3, input_price = $4, output_price = $5, cached_input_price = $6
where id = $1 and channel_id = $2
returning id, name, input_price, output_price, cached_input_price, created_at
`

type UpdateChannelModelParams struct {
	ID               uuid.UUID
	ChannelID        uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
}

type UpdateChannelModelRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) UpdateChannelModel(ctx context.Context, arg UpdateChannelModelParams) (UpdateChannelModelRow, error) {
	row := q.db.QueryRow(ctx, updateChannelModel,
		arg.ID,
		arg.ChannelID,
		arg.Name,
		arg.InputPrice,
		arg.OutputPrice,
		arg.CachedInputPrice,
	)
	var i UpdateChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.CreatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
update roles set name = $2, permissions = $3
where id = $1
returning id, name, built_in, permissions
`

type UpdateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Permissions []byte
}

type UpdateRoleRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (UpdateRoleRow, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Permissions)
	var i UpdateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
update users set password_hash = $2 where id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserRole = `-- name: UpdateUserRole :execrows
update users set role_id = $2 where id = $1
`

type UpdateUserRoleParams struct {
	ID     uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
