//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CaseMode.
const (
	NonStream CaseMode = "non_stream"
	Stream    CaseMode = "stream"
)

// Valid indicates whether the value is a known member of the CaseMode enum.
func (e CaseMode) Valid() bool {
	switch e {
	case NonStream:
		return true
	case Stream:
		return true
	default:
		return false
	}
}

// Defines values for CaseStatus.
const (
	Passed   CaseStatus = "passed"
	Rejected CaseStatus = "rejected"
	Violated CaseStatus = "violated"
)

// Valid indicates whether the value is a known member of the CaseStatus enum.
func (e CaseStatus) Valid() bool {
	switch e {
	case Passed:
		return true
	case Rejected:
		return true
	case Violated:
		return true
	default:
		return false
	}
}

// Defines values for CostTier.
const (
	Cheap     CostTier = "cheap"
	Expensive CostTier = "expensive"
	Medium    CostTier = "medium"
)

// Valid indicates whether the value is a known member of the CostTier enum.
func (e CostTier) Valid() bool {
	switch e {
	case Cheap:
		return true
	case Expensive:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for Currency.
const (
	CNY Currency = "CNY"
	USD Currency = "USD"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case CNY:
		return true
	case USD:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Protocol.
const (
	AnthropicMessages Protocol = "anthropic_messages"
	OpenaiChat        Protocol = "openai_chat"
	OpenaiResponses   Protocol = "openai_responses"
)

// Valid indicates whether the value is a known member of the Protocol enum.
func (e Protocol) Valid() bool {
	switch e {
	case AnthropicMessages:
		return true
	case OpenaiChat:
		return true
	case OpenaiResponses:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	Canceled  TaskStatus = "canceled"
	Failed    TaskStatus = "failed"
	Queued    TaskStatus = "queued"
	Running   TaskStatus = "running"
	Succeeded TaskStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// CaseMode defines model for CaseMode.
type CaseMode string

// CaseStatus 用例判定：rejected=请求被上游拒绝（HTTP/传输错误）；violated=响应到手但不合规；passed=合规
type CaseStatus string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// Channel defines model for Channel.
type Channel struct {
	// BaseUrl 填到版本段（如 https://api.example.com/v1），平台按协议拼固定末段
	BaseUrl   string    `json:"baseUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency Currency `json:"currency"`

	// Disabled 停用后不可选入新检测任务，配置与 key 保留
	Disabled bool               `json:"disabled"`
	Id       openapi_types.UUID `json:"id"`

	// KeyPrefix API key 脱敏前缀（key 写后不可回读）
	KeyPrefix  string            `json:"keyPrefix"`
	LastTest   *ConnectivityTest `json:"lastTest,omitempty"`
	ModelCount int               `json:"modelCount"`
	Name       string            `json:"name"`
	Note       string            `json:"note"`
	Protocols  []Protocol        `json:"protocols"`
}

// ChannelCreate defines model for ChannelCreate.
type ChannelCreate struct {
	ApiKey string `json:"apiKey"`

	// BaseUrl 填到版本段（如 https://api.example.com/v1），末尾斜杠会被自动去除
	BaseUrl string `json:"baseUrl"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency  *Currency  `json:"currency,omitempty"`
	Name      string     `json:"name"`
	Note      *string    `json:"note,omitempty"`
	Protocols []Protocol `json:"protocols"`
}

// ChannelDetail defines model for ChannelDetail.
type ChannelDetail struct {
	// BaseUrl 填到版本段（如 https://api.example.com/v1），平台按协议拼固定末段
	BaseUrl   string    `json:"baseUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency Currency `json:"currency"`

	// Disabled 停用后不可选入新检测任务，配置与 key 保留
	Disabled bool               `json:"disabled"`
	Id       openapi_types.UUID `json:"id"`

	// KeyPrefix API key 脱敏前缀（key 写后不可回读）
	KeyPrefix  string            `json:"keyPrefix"`
	LastTest   *ConnectivityTest `json:"lastTest,omitempty"`
	ModelCount int               `json:"modelCount"`
	Models     []ModelEntry      `json:"models"`
	Name       string            `json:"name"`
	Note       string            `json:"note"`
	Protocols  []Protocol        `json:"protocols"`
}

// ChannelUpdate defines model for ChannelUpdate.
type ChannelUpdate struct {
	// ApiKey 缺省=不改；给值=整体覆盖
	ApiKey  *string `json:"apiKey,omitempty"`
	BaseUrl *string `json:"baseUrl,omitempty"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency  *Currency   `json:"currency,omitempty"`
	Disabled  *bool       `json:"disabled,omitempty"`
	Name      *string     `json:"name,omitempty"`
	Note      *string     `json:"note,omitempty"`
	Protocols *[]Protocol `json:"protocols,omitempty"`
}

// ConnectivityResult defines model for ConnectivityResult.
type ConnectivityResult struct {
	// Error 失败摘要（超时/连接错误/上游错误体截断）
	Error *string `json:"error,omitempty"`
	Ok    bool    `json:"ok"`

	// Protocol 渠道支持的接口协议
	Protocol Protocol `json:"protocol"`

	// Status 上游 HTTP 状态码（网络层失败时缺省）
	Status *int `json:"status,omitempty"`

	// TtftMs 首字延迟毫秒（流式首个数据帧到达；失败时缺省）
	TtftMs *int `json:"ttftMs,omitempty"`
}

// ConnectivityTest defines model for ConnectivityTest.
type ConnectivityTest struct {
	// Model 当时用于探测的模型名（快照，不随模型条目改名变化）
	Model    string               `json:"model"`
	Results  []ConnectivityResult `json:"results"`
	TestedAt time.Time            `json:"testedAt"`
}

// ConnectivityTestRequest defines model for ConnectivityTestRequest.
type ConnectivityTestRequest struct {
	// ModelId 用哪个模型条目发探测请求
	ModelId openapi_types.UUID `json:"modelId"`
}

// CostTier 烧钱等级（便宜的挡在贵的前面）
type CostTier string

// Currency 渠道定价币种（仅标注，不做汇率换算）
type Currency string

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	Id openapi_types.UUID `json:"id"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions PermissionMap `json:"permissions"`
	Role        string        `json:"role"`
	Username    string        `json:"username"`
}

// DeployRequest defines model for DeployRequest.
type DeployRequest struct {
	// Tag 要部署的版本 tag（须是已存在的 GitHub Release）
	Tag string `json:"tag"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// ModelEntry defines model for ModelEntry.
type ModelEntry struct {
	CachedInputPrice *float32           `json:"cachedInputPrice,omitempty"`
	CreatedAt        time.Time          `json:"createdAt"`
	Id               openapi_types.UUID `json:"id"`

	// InputPrice 每 1M token 输入单价（币种见渠道）；三个价格字段全缺省=未定价
	InputPrice  *float32 `json:"inputPrice,omitempty"`
	Name        string   `json:"name"`
	OutputPrice *float32 `json:"outputPrice,omitempty"`
}

// ModelEntryUpsert 输入/输出价须成对出现；缓存读价只能在前两者存在时给出（服务端校验）
type ModelEntryUpsert struct {
	CachedInputPrice *float32 `json:"cachedInputPrice,omitempty"`
	InputPrice       *float32 `json:"inputPrice,omitempty"`
	Name             string   `json:"name"`
	OutputPrice      *float32 `json:"outputPrice,omitempty"`
}

// PermissionMap 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
type PermissionMap struct {
	Channels  bool `json:"channels"`
	Quality   bool `json:"quality"`
	Stability bool `json:"stability"`
	System    bool `json:"system"`
	Users     bool `json:"users"`
}

// ProbeInfo defines model for ProbeInfo.
type ProbeInfo struct {
	// CaseCount 全量用例数
	CaseCount int `json:"caseCount"`

	// CostTier 烧钱等级（便宜的挡在贵的前面）
	CostTier    CostTier `json:"costTier"`
	Description string   `json:"description"`

	// Id 检测项唯一标识（如 tool_call_json_schema）
	Id string `json:"id"`

	// Name 中文显示名
	Name string `json:"name"`

	// NeedsControl 是否需要对照渠道
	NeedsControl bool `json:"needsControl"`

	// NeedsPricing 是否要求目标模型已定价
	NeedsPricing bool `json:"needsPricing"`

	// Protocols 适用协议（渠道须至少声明其中之一）
	Protocols []Protocol `json:"protocols"`

	// RequestsPerCase 每用例请求数（如 toolschema 非流式+流式各一次 = 2），用于前端估算请求量
	RequestsPerCase int `json:"requestsPerCase"`

	// SupportsMaxCases 是否受任务参数「用例数上限」影响（固定请求矩阵的检测项为 false）
	SupportsMaxCases bool `json:"supportsMaxCases"`
}

// Protocol 渠道支持的接口协议
type Protocol string

// QualityCaseResult defines model for QualityCaseResult.
type QualityCaseResult struct {
	// Arguments 模型最终产出的工具参数原文（截断存储）
	Arguments  *string `json:"arguments,omitempty"`
	Attempts   int     `json:"attempts"`
	HttpStatus *int    `json:"httpStatus,omitempty"`
	LatencyMs  *int    `json:"latencyMs,omitempty"`

	// Line 套件内行号（1 起，与 KVV 官方报告对齐）
	Line int `json:"line"`

	// Message 失败摘要（校验错误/上游错误体截断；通过时为空）
	Message         string   `json:"message"`
	Mode            CaseMode `json:"mode"`
	Probe           string   `json:"probe"`
	SelectionReason string   `json:"selectionReason"`

	// Status 用例判定：rejected=请求被上游拒绝（HTTP/传输错误）；violated=响应到手但不合规；passed=合规
	Status CaseStatus `json:"status"`

	// Suite 语料套件名（如 TestEnforcerCases）
	Suite string `json:"suite"`
}

// QualityTask defines model for QualityTask.
type QualityTask struct {
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy 创建者用户名（用户被删后缺省）
	CreatedBy *string `json:"createdBy,omitempty"`

	// Error 任务级失败原因（用例级失败不算任务失败）
	Error         *string            `json:"error,omitempty"`
	FinishedAt    *time.Time         `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	Params        QualityTaskParams  `json:"params"`
	Probes        []string           `json:"probes"`
	ProgressDone  int                `json:"progressDone"`
	ProgressTotal int                `json:"progressTotal"`
	StartedAt     *time.Time         `json:"startedAt,omitempty"`
	Stats         *TaskStats         `json:"stats,omitempty"`
	Status        TaskStatus         `json:"status"`

	// Target 检测对象参数快照（任务创建时定格，不受渠道后续编辑/删除影响；绝不含 API key）
	Target TaskTarget `json:"target"`
}

// QualityTaskCreate defines model for QualityTaskCreate.
type QualityTaskCreate struct {
	ChannelId    openapi_types.UUID `json:"channelId"`
	ModelEntryId openapi_types.UUID `json:"modelEntryId"`
	Params       *QualityTaskParams `json:"params,omitempty"`

	// Probes 勾选的检测项 id 集合
	Probes []string `json:"probes"`
}

// QualityTaskList defines model for QualityTaskList.
type QualityTaskList struct {
	Items []QualityTask `json:"items"`
	Total int           `json:"total"`
}

// QualityTaskParams defines model for QualityTaskParams.
type QualityTaskParams struct {
	// Concurrency 任务内请求并发数
	Concurrency *int `json:"concurrency,omitempty"`

	// MaxCases 用例数上限（缺省=全量；超过检测项全量数时按全量算）
	MaxCases *int `json:"maxCases,omitempty"`

	// Reruns 失败用例重跑轮数（末次结果为准）
	Reruns *int `json:"reruns,omitempty"`
}

// Role defines model for Role.
type Role struct {
	BuiltIn bool               `json:"builtIn"`
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions PermissionMap `json:"permissions"`
}

// RoleCreate defines model for RoleCreate.
type RoleCreate struct {
	Name string `json:"name"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions PermissionMap `json:"permissions"`
}

// RoleUpdate defines model for RoleUpdate.
type RoleUpdate struct {
	Name *string `json:"name,omitempty"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions *PermissionMap `json:"permissions,omitempty"`
}

// TaskStatBucket defines model for TaskStatBucket.
type TaskStatBucket struct {
	Name     string `json:"name"`
	Passed   int    `json:"passed"`
	Rejected int    `json:"rejected"`
	Total    int    `json:"total"`
	Violated int    `json:"violated"`
}

// TaskStats defines model for TaskStats.
type TaskStats struct {
	ByMode []TaskStatBucket `json:"byMode"`

	// ByReason 按选例理由（selection_reason）分桶
	ByReason []TaskStatBucket `json:"byReason"`
	Passed   int              `json:"passed"`
	Rejected int              `json:"rejected"`
	Total    int              `json:"total"`
	Violated int              `json:"violated"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TaskTarget 检测对象参数快照（任务创建时定格，不受渠道后续编辑/删除影响；绝不含 API key）
type TaskTarget struct {
	BaseUrl          string   `json:"baseUrl"`
	CachedInputPrice *float32 `json:"cachedInputPrice,omitempty"`

	// ChannelId 原渠道 id（渠道被删后仅作历史参考）
	ChannelId   *openapi_types.UUID `json:"channelId,omitempty"`
	ChannelName string              `json:"channelName"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency     *Currency           `json:"currency,omitempty"`
	InputPrice   *float32            `json:"inputPrice,omitempty"`
	Model        string              `json:"model"`
	ModelEntryId *openapi_types.UUID `json:"modelEntryId,omitempty"`
	OutputPrice  *float32            `json:"outputPrice,omitempty"`
	Protocols    []Protocol          `json:"protocols"`
}

// UpdateStatus defines model for UpdateStatus.
type UpdateStatus struct {
	CurrentVersion string     `json:"currentVersion"`
	LatestVersion  *string    `json:"latestVersion,omitempty"`
	PublishedAt    *time.Time `json:"publishedAt,omitempty"`
	ReleaseNotes   *string    `json:"releaseNotes,omitempty"`

	// TokenConfigured 服务器是否配置了 GitHub Token（未配置时无法检查/触发更新）
	TokenConfigured bool `json:"tokenConfigured"`
	UpdateAvailable bool `json:"updateAvailable"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	RoleId    openapi_types.UUID `json:"roleId"`
	RoleName  string             `json:"roleName"`
	Username  string             `json:"username"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Password string             `json:"password"`
	RoleId   openapi_types.UUID `json:"roleId"`
	Username string             `json:"username"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Password *string             `json:"password,omitempty"`
	RoleId   *openapi_types.UUID `json:"roleId,omitempty"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	Version string `json:"version"`
}

// IdPath defines model for IdPath.
type IdPath = openapi_types.UUID

// ModelIdPath defines model for ModelIdPath.
type ModelIdPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListQualityTasksParams defines parameters for ListQualityTasks.
type ListQualityTasksParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListQualityTaskResultsParams defines parameters for ListQualityTaskResults.
type ListQualityTaskResultsParams struct {
	Status *CaseStatus `form:"status,omitempty" json:"status,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangeOwnPasswordJSONRequestBody defines body for ChangeOwnPassword for application/json ContentType.
type ChangeOwnPasswordJSONRequestBody = ChangePasswordRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = ChannelCreate

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = ChannelUpdate

// AddChannelModelJSONRequestBody defines body for AddChannelModel for application/json ContentType.
type AddChannelModelJSONRequestBody = ModelEntryUpsert

// UpdateChannelModelJSONRequestBody defines body for UpdateChannelModel for application/json ContentType.
type UpdateChannelModelJSONRequestBody = ModelEntryUpsert

// TestChannelJSONRequestBody defines body for TestChannel for application/json ContentType.
type TestChannelJSONRequestBody = ConnectivityTestRequest

// CreateQualityTaskJSONRequestBody defines body for CreateQualityTask for application/json ContentType.
type CreateQualityTaskJSONRequestBody = QualityTaskCreate

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleCreate

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = RoleUpdate

// TriggerDeployJSONRequestBody defines body for TriggerDeploy for application/json ContentType.
type TriggerDeployJSONRequestBody = DeployRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreate

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 登录，成功后通过 HttpOnly Cookie 建立会话
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout 登出，销毁当前会话
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetCurrentUser 获取当前登录用户（含角色与模块权限）
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// ChangeOwnPassword 修改自己的密码（需验证当前密码，成功后注销其他会话）
	// (PUT /auth/password)
	ChangeOwnPassword(w http.ResponseWriter, r *http.Request)
	// ListChannels 渠道列表（需 channels 权限）
	// (GET /channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// CreateChannel 创建渠道（需 channels 权限；模型条目建完后在详情页添加）
	// (POST /channels)
	CreateChannel(w http.ResponseWriter, r *http.Request)
	// DeleteChannel 删除渠道（需 channels 权限；硬删，历史任务持有参数快照不受影响，key 不可恢复）
	// (DELETE /channels/{id})
	DeleteChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetChannel 渠道详情（需 channels 权限；含模型条目列表）
	// (GET /channels/{id})
	GetChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// UpdateChannel 修改渠道基本信息（需 channels 权限；apiKey 缺省=不改、给值=覆盖，写后不可回读）
	// (PATCH /channels/{id})
	UpdateChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// AddChannelModel 添加模型条目（需 channels 权限）
	// (POST /channels/{id}/models)
	AddChannelModel(w http.ResponseWriter, r *http.Request, id IdPath)
	// DeleteChannelModel 删除模型条目（需 channels 权限；历史任务持有参数快照不受影响）
	// (DELETE /channels/{id}/models/{modelId})
	DeleteChannelModel(w http.ResponseWriter, r *http.Request, id IdPath, modelId ModelIdPath)
	// UpdateChannelModel 全量替换模型条目（需 channels 权限；缺省的价格字段即清空为未定价）
	// (PUT /channels/{id}/models/{modelId})
	UpdateChannelModel(w http.ResponseWriter, r *http.Request, id IdPath, modelId ModelIdPath)
	// TestChannel 连通测试（需 channels 权限；对每个已声明协议发 max_tokens=1 最小真实请求，结果落库为该渠道最近一次测试）
	// (POST /channels/{id}/test)
	TestChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetHealthz 健康检查
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListProbes 检测项注册表（需 quality 权限；含元数据供发起页勾选）
	// (GET /probes)
	ListProbes(w http.ResponseWriter, r *http.Request)
	// ListQualityTasks 质量检测任务历史（需 quality 权限；按创建时间倒序）
	// (GET /quality/tasks)
	ListQualityTasks(w http.ResponseWriter, r *http.Request, params ListQualityTasksParams)
	// CreateQualityTask 创建质量检测任务（需 quality 权限；创建时快照检测对象参数，入队后由 worker 执行）
	// (POST /quality/tasks)
	CreateQualityTask(w http.ResponseWriter, r *http.Request)
	// GetQualityTask 任务详情（需 quality 权限；含参数快照与聚合统计）
	// (GET /quality/tasks/{id})
	GetQualityTask(w http.ResponseWriter, r *http.Request, id IdPath)
	// CancelQualityTask 取消任务（需 quality 权限；排队或运行中的任务可取消，运行中的中止在途请求）
	// (POST /quality/tasks/{id}/cancel)
	CancelQualityTask(w http.ResponseWriter, r *http.Request, id IdPath)
	// StreamQualityTaskEvents 任务进度事件流（需 quality 权限；SSE，连接后先推当前快照，任务终态后关闭）
	// (GET /quality/tasks/{id}/events)
	StreamQualityTaskEvents(w http.ResponseWriter, r *http.Request, id IdPath)
	// ListQualityTaskResults 用例级结果（需 quality 权限；可按判定状态过滤）
	// (GET /quality/tasks/{id}/results)
	ListQualityTaskResults(w http.ResponseWriter, r *http.Request, id IdPath, params ListQualityTaskResultsParams)
	// ListRoles 角色列表（需 users 权限）
	// (GET /roles)
	ListRoles(w http.ResponseWriter, r *http.Request)
	// CreateRole 创建角色（需 users 权限）
	// (POST /roles)
	CreateRole(w http.ResponseWriter, r *http.Request)
	// DeleteRole 删除角色（需 users 权限；内置角色与仍被使用的角色不可删除）
	// (DELETE /roles/{id})
	DeleteRole(w http.ResponseWriter, r *http.Request, id IdPath)
	// UpdateRole 修改角色名或权限（需 users 权限；内置角色不可修改）
	// (PATCH /roles/{id})
	UpdateRole(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetUpdateStatus 检查在线更新（需 system 权限；查询 GitHub 最新 Release）
	// (GET /system/update)
	GetUpdateStatus(w http.ResponseWriter, r *http.Request)
	// TriggerDeploy 触发在线更新（需 system 权限；调 GitHub Actions 重新部署指定版本）
	// (POST /system/update/deploy)
	TriggerDeploy(w http.ResponseWriter, r *http.Request)
	// ListUsers 用户列表（需 users 权限）
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// CreateUser 创建用户（需 users 权限；不开放注册，账号只能在此创建）
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser 删除用户（需 users 权限；不能删除自己）
	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id IdPath)
	// UpdateUser 修改用户角色或重置密码（需 users 权限；不能改自己的角色）
	// (PATCH /users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetVersion 当前服务版本
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeOwnPassword operation middleware
func (siw *ServerInterfaceWrapper) ChangeOwnPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeOwnPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannel operation middleware
func (siw *ServerInterfaceWrapper) GetChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChannel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddChannelModel operation middleware
func (siw *ServerInterfaceWrapper) AddChannelModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddChannelModel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannelModel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannelModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "modelId" -------------
	var modelId ModelIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "modelId", r.PathValue("modelId"), &modelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannelModel(w, r, id, modelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChannelModel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannelModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "modelId" -------------
	var modelId ModelIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "modelId", r.PathValue("modelId"), &modelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChannelModel(w, r, id, modelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestChannel operation middleware
func (siw *ServerInterfaceWrapper) TestChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProbes operation middleware
func (siw *ServerInterfaceWrapper) ListProbes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProbes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQualityTasks operation middleware
func (siw *ServerInterfaceWrapper) ListQualityTasks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListQualityTasksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQualityTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQualityTask operation middleware
func (siw *ServerInterfaceWrapper) CreateQualityTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQualityTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQualityTask operation middleware
func (siw *ServerInterfaceWrapper) GetQualityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQualityTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelQualityTask operation middleware
func (siw *ServerInterfaceWrapper) CancelQualityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelQualityTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamQualityTaskEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamQualityTaskEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamQualityTaskEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQualityTaskResults operation middleware
func (siw *ServerInterfaceWrapper) ListQualityTaskResults(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListQualityTaskResultsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQualityTaskResults(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoles operation middleware
func (siw *ServerInterfaceWrapper) ListRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRole operation middleware
func (siw *ServerInterfaceWrapper) CreateRole(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRole(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRole operation middleware
func (siw *ServerInterfaceWrapper) DeleteRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUpdateStatus operation middleware
func (siw *ServerInterfaceWrapper) GetUpdateStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUpdateStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerDeploy operation middleware
func (siw *ServerInterfaceWrapper) TriggerDeploy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerDeploy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/auth/password", wrapper.ChangeOwnPassword)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/users/{id}", wrapper.UpdateUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/roles", wrapper.ListRoles)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/roles", wrapper.CreateRole)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/roles/{id}", wrapper.DeleteRole)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/roles/{id}", wrapper.UpdateRole)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/channels", wrapper.ListChannels)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/channels", wrapper.CreateChannel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/channels/{id}", wrapper.DeleteChannel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/channels/{id}", wrapper.GetChannel)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/channels/{id}", wrapper.UpdateChannel)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/channels/{id}/models", wrapper.AddChannelModel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/channels/{id}/models/{modelId}", wrapper.DeleteChannelModel)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/channels/{id}/models/{modelId}", wrapper.UpdateChannelModel)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/channels/{id}/test", wrapper.TestChannel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/system/update", wrapper.GetUpdateStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/system/update/deploy", wrapper.TriggerDeploy)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/probes", wrapper.ListProbes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks", wrapper.ListQualityTasks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quality/tasks", wrapper.CreateQualityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}", wrapper.GetQualityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}/results", wrapper.ListQualityTaskResults)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quality/tasks/{id}/cancel", wrapper.CancelQualityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}/events", wrapper.StreamQualityTaskEvents)

	return m
}
